### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by milutinke** [Spishous/Crack-PhpStorm-2021.1.4#1]
Can we get the source code?
How we can know that this is not malicious.

**Comment by Spishous** [comment]
Hi @milutinke 
I don't have the source code for the file, but it's not malicious. I have been using this crack for 1 year.
If you follow the guide, you can see that adding the .jar file just allows you to enter the license key.
And with the "hosts" file, you must block the license verification to the Jetbrains servers when starting PhpStorm

PS: If you wish, I can add a ".readme" in English

**Comment by milutinke** [comment]
I've translated the readme no need to translate it
Thanks for the reply
